name: Program Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  program-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Solana Anchor Test
        uses: mrgnlabs/anchor-test-action@v0.5
