anchor_version = "0.28.0"
solana_version = "1.16.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
pre-authorized-debit-v1 = "HjJXoCqUmn6VQzXLqA1pEvWRZZcEMbD2HGixXKrs7DQj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./test-keypair.json"

[scripts]
test = "node scripts/test.js"
