anchor_version = "0.28.0"
solana_version = "1.16.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
pre_authorized_debit_v1 = "Debit3fDrmgHiJpc5rhxi1YjsWtbupdSLaCRE1Xk7fhT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./test-keypair.json"

[scripts]
test = "node scripts/test.js"
