anchor_version = "0.28.0"
solana_version = "1.16.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
pre_authorized_debit_v1 = "PadV1i1My8wazb6vi37UJ2s1yBDkFN5MYivYN6XgaaR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./test-keypair.json"

[scripts]
test = "node scripts/test.js"

[test]
startup_wait=10000
