anchor_version = "0.28.0"
solana_version = "1.16.10"

[features]
seeds = false
skip-lint = false
[programs.localnet]
pre-authorized-debits-v1 = "HjJXoCqUmn6VQzXLqA1pEvWRZZcEMbD2HGixXKrs7DQj"
smart_account_v1 = "3FWaGq3zYcqJq2t4tszrTAwVrLTc1BcAZzVGLAbK7piR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./test-keypair.json"

[scripts]
test = "node scripts/test.js"
