name: Program Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [ready_for_review]
jobs:
  program-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Solana Anchor Test
        uses: dcaf-labs/anchor-test-action@v1.1.0
        with:
          # add anchor test args, e.g. "--skip-lint"
          args: ""
          # path to the anchor workspace, e.g. "./my_workspace"
          workspace_dir: "."

  # TODO: this is wasting some credits as it is re-compiling and re-installing packages
  program-tests-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Solana Anchor Test
        uses: dcaf-labs/anchor-test-action@v1.1.0
        with:
          args: 'pre-authorized-debit-v1 .2.ts'
          workspace_dir: "."
