name: Program Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  program-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Solana Anchor Test
        uses: dcaf-labs/pre-authorized-debit/.github/actions/solana-anchor-test.yml@main
