name: Program Tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [ready_for_review]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  program-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          [
            "anchor test pre-authorized-debit-v1 .ts",
            "anchor test pre-authorized-debit-v1 .2.ts",
            "anchor test pre-authorized-debit-v1/debit .ts",
            "cargo test",
          ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Test
        uses: dcaf-labs/anchor-test-action@v2.0.0
        with:
          # add anchor test args, e.g. "--skip-lint"
          command: "${{ matrix.command }}"
          # path to the anchor workspace, e.g. "./my_workspace"
          workspace_dir: "."
