name: Program Tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.28.0
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup default stable
      - run: cargo test

  program-integration-tests:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.28.0
    strategy:
      matrix:
        testSuffix: [ ".ts", ".2.ts" ]
    steps:
      - uses: actions/checkout@v3
      - name: Yarn cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: Swatinem/rust-cache@v2
      - run: rustup default stable
      - run: solana-keygen new --no-bip39-passphrase
      - run: solana config set --url http:localhost:8899
      - run: yarn install
      - run: anchor test --arch sbf "**" ${{ matrix.testSuffix }}
