name: SDK Tests

on:
  pull_request:
  push:
    paths:
      - "sdk/**/*"
      - "package.json"
      - "yarn.lock"
      - ".github/workflows/sdk-tests.yaml"
    branches:
      - main
      - feat/**/*

concurrency:
  group: ${{ github.ref }}-sdk-tests
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup | checkout
        uses: actions/checkout@v3
      - name: Setup | node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "yarn"
      - name: Caching node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
      - name: Setup | yarn deps
        run: yarn install

  lint:
    needs: ["install"]
    runs-on: ubuntu-20.04
    steps:
      - name: Setup | checkout
        uses: actions/checkout@v3
      - name: Setup | node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "yarn"
      - name: Setup | cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
      - name: Lint
        run: yarn lint

  build:
    needs: ["install", "lint"]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        sdk: ["pre-authorized-debit-v1"]
    steps:
      - name: Setup | checkout
        uses: actions/checkout@v3
      - name: Setup | node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "yarn"
      - name: Setup | cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
      - name: Build
        run: cd ./sdk/${{ matrix.sdk }} && yarn build

  test:
    needs: ["build"]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        sdk: ["pre-authorized-debit-v1"]
    steps:
      - name: Setup | checkout
        uses: actions/checkout@v3
      - name: Setup | node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "yarn"
      - name: Setup | cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
      - name: Test | Run Jest
        run: cd ./sdk/${{ matrix.sdk }} && yarn test
      - name: Test | Code Coverage
        uses: jpb06/jest-badges-action@latest
        with:
          coverage-summary-path: ./sdk/${{ matrix.sdk }}/coverage/coverage-summary.json
          branches: main,feat/sdk
          commit-user: Seabed CI
          commit-user-email: devtools@dcaf.so
          output-folder: ./sdk/${{ matrix.sdk }}/badges
