#name: SDK Tests
#
#on:
#  pull_request:
#  push:
#    paths:
#      - "sdk/**/*"
#      - "package.json"
#      - "yarn.lock"
#      - ".github/workflows/sdk-tests.yaml"
#    branches:
#      - main
#      - feat/**/*
#
#concurrency:
#  group: ${{ github.ref }}-sdk-tests
#  cancel-in-progress: true
#
#jobs:
#  install:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Setup | checkout
#        uses: actions/checkout@v3
#      - name: Setup | node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.17.1
#          cache: "yarn"
#      - name: Caching node modules
#        uses: actions/cache@v2
#        with:
#          path: "**/node_modules"
#          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
#      - name: Setup | yarn deps
#        run: yarn install
#
#  lint:
#    needs: ["install"]
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Setup | checkout
#        uses: actions/checkout@v3
#      - name: Setup | node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.17.1
#          cache: "yarn"
#      - name: Setup | cache node modules
#        uses: actions/cache@v2
#        with:
#          path: "**/node_modules"
#          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
#      - name: Lint
#        run: yarn lint
#
#  build:
#    needs: ["install", "lint"]
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        sdk: ["pre-authorized-debit-v1"]
#    steps:
#      - name: Setup | checkout
#        uses: actions/checkout@v3
#      - name: Setup | node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.17.1
#          cache: "yarn"
#      - name: Setup | cache node modules
#        uses: actions/cache@v2
#        with:
#          path: "**/node_modules"
#          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
#      - name: Build
#        run: cd ./sdk/${{ matrix.sdk }} && yarn build
#
#  test:
#    needs: ["build"]
#    runs-on: ubuntu-20.04
#    strategy:
#      matrix:
#        sdk: ["pre-authorized-debit-v1"]
#    steps:
#      - name: Setup | checkout
#        uses: actions/checkout@v3
#      - name: Setup | node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.17.1
#          cache: "yarn"
#      - name: Setup | cache node modules
#        uses: actions/cache@v2
#        with:
#          path: "**/node_modules"
#          key: node-modules-${{ hashFiles('**/package.json', 'yarn.lock') }}
#      - name: Setup | rust cache
#        uses: Swatinem/rust-cache@v2
#        with:
#          prefix-key: "sdk-tests"
#          shared-key: "sdk-tests"
#      - name: Setup | cache crates
#        uses: metaplex-foundation/actions/cache-crates@v1
#      - name: Setup | rust
#        uses: metaplex-foundation/actions/install-rust@v1
#      - name: Setup | anchor
#        run: yarn global add @coral-xyz/anchor-cli@0.28.0
#      - name: Setup | solana
#        uses: metaplex-foundation/actions/install-solana@v1
#        with:
#          version: 1.16.10
#          cache: true
#      - name: Setup | solana keypair
#        run: solana-keygen new --no-bip39-passphrase
#      - name: Setup | solana url
#        run: solana config set --url http:localhost:8899
#      - name: Setup | anchor build
#        run: anchor build
##      - name: Setup | Start Validator
##        run: solana-test-validator --reset&
##      - name: Setup | airdrop local provider
##        run: solana airdrop 500000 8QauqZxeMf3apzvQ8hYxSD1SAdb5VfL92eT63WHnZmzZ
##      - name: Setup | deploy local programs
##        run: anchor deploy --provider.cluster "http://localhost:8899" --provider.wallet ./test-keypair.json
##      - name: Test | run jest
##        env:
##          DEVNET_VALIDATOR_URL: ${{ secrets.DEVNET_VALIDATOR_URL }}
##          MAINNET_VALIDATOR_URL: ${{ secrets.MAINNET_VALIDATOR_URL }}
##        run: cd ./sdk/${{ matrix.sdk }} && yarn test
##      - name: Test | stop validator
##        run: kill $(lsof -t -i:9900)
##      - name: Test | code coverage
##        uses: jpb06/jest-badges-action@latest
##        with:
##          coverage-summary-path: ./sdk/${{ matrix.sdk }}/coverage/coverage-summary.json
##          branches: main,feat/sdk
##          commit-user: Seabed CI
##          commit-user-email: devtools@dcaf.so
##          output-folder: ./sdk/${{ matrix.sdk }}/badges
